import antfu from '@antfu/eslint-config'

export default antfu(
  {
    vue: true,
    typescript: true,
    formatters: false,
    // Config JSON (tsconfig etc.) isn't app code — key-ordering rules there would just be churn.
    jsonc: false,
    // Vendored shadcn-vue primitives: generated by its CLI, not hand-written, and
    // reformatting them would just drift from what a future `shadcn-vue add` regenerates.
    ignores: ['src/components/ui/**'],
  },
  {
    rules: {
      // CLAUDE.md: "Avoid `any`."
      'ts/no-explicit-any': 'error',
    },
  },
)
